# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CORE', '0003_printmodel_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='printmodel',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
