# Generated by Django 2.2.2 on 2019-07-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0007_object_pk_type'),
        ('framework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LucteriosLogEntry',
            fields=[
            ],
            options={
                'verbose_name': 'log entry',
                'verbose_name_plural': 'log entries',
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'proxy': True,
                'default_permissions': [],
                'indexes': [],
                'constraints': [],
            },
            bases=('auditlog.logentry', ),
        ),
    ]
